### PR TITLE
Add a build script to create cli binaries for different architectures and operating systems

### PR DESCRIPTION
**Pull request by ikhoon**
We don't build and publish Central Dogma binaries on a regular basis yet. A build script and manual uploading would be sufficient at the moment.

This will resolve the Apple silicon support in Central Dogma cli https://github.com/line/centraldogma/issues/779

### CODE REVIEW

**Review by minwoox — APPROVED** [review]
Thanks!

**Comment by clavinjune** [comment]
was looking at [this](https://goreleaser.com), it might helps for more advance configuration if you don't want to reinvent the wheel

**Review by trustin — APPROVED** [review]

**Comment by trustin** [comment]
> was looking at [this](https://goreleaser.com), it might helps for more advance configuration if you don't want to reinvent the wheel

Looks neat! Shall we create an issue so we can follow up?

**Review by jrhee17 — APPROVED** [review]
👍 👍 👍

**Pull request merged**
