### PR TITLE
feat(Breaking change) : match revision type to int64

### PR DESCRIPTION
**Pull request by jinwoo1225**
- propose revision type to be int64
- Entry Type has int64, but none other has revision typed of int64

Thanks for great project 🥰

### CODE REVIEW

**Review by linxGnu — APPROVED** [review]
LGTM. Thank you for contributing @jinwoo1225

**Comment by linxGnu** [comment]
@jinwoo1225 could you please fix the test. I believe the problem come from incompatible type.

you could use `require.EqualValues` instead of `require.Equal` to fix it. And please try to run unit test at your local

**Comment by jinwoo1225** [comment]
@linxGnu Thanks for information, I will fix it right away! 😃

**Comment by jinwoo1225** [comment]
tested by `go test -v -race -coverprofile coverage.txt -covermode atomic ./...` command. 6344f0b
```bash
PASS
coverage: 76.7% of statements
ok      go.linecorp.com/centraldogma    25.819s coverage: 76.7% of statements
```

**Comment by ikhoon** [comment]
Technically, the maximum allowed number of commits in a repository is `Integer.MAX_VALUE` (2^31 - 1).
https://github.com/ikhoon/centraldogma/blob/master/common/src/main/java/com/linecorp/centraldogma/common/Revision.java#L115-L120
Is there a special reason that you have to use `int64`? Otherwise, how about changing `Entry.Revision` into `int`?

**Comment by jinwoo1225** [comment]
@ikhoon for first, thanks for reply and sorry for misunderstand of mine about centraldogma...
I naively thought every revision of repository was based on `int64` by checking `Entry.Revision`'s type...
so I will republish PR that will change `Entry.Revision` type to `int32`

if you checked this comment, would you close this PR?...

**Comment by linxGnu** [comment]
Just IMHO, its better to make it the same as server. Int32 looks like a good option to me.

**Comment by jinwoo1225** [comment]
Sure! if server deliver int32 typed, client should take int32. 😆

**Comment by minwoox** [comment]
I'm really sorry that I didn't use the proper type from the first. 😅 

I guess it's time for us to define `Revision` type and use it.
If so, we can define additional fields such as `Revision.HEAD` and `Revision.INIT` to use as we do in the upstream.

**Comment by jinwoo1225** [comment]
@minwoox no need to sorry me 😊

In my knowledge `HEAD` is latest revision of repository but what is `INIT`?

**Comment by jrhee17** [comment]
If I understand correctly, `Revision.INIT` represents the first commit for a git repository.

The definition can be found [upstream].(https://github.com/line/centraldogma/blob/3642633f396b0ff18db3651190908e9654df9eec/common/src/main/java/com/linecorp/centraldogma/common/Revision.java#L61)

**Comment by ikhoon** [comment]
Let me close this PR in favor of #47

**Pull request closed without merging**
