### PR TITLE
Modernize urfave-cli

### PR DESCRIPTION
**Pull request by clavinjune**
related to #53

### CODE REVIEW

**Comment by clavinjune** [comment]
bumping this up 🙇‍♂️

**Review by trustin — APPROVED** [review]
Thanks for updating the dependency, @clavinjune! 🙇

**Review by minwoox — APPROVED** [review]
Thanks, @clavinjune! 🙇‍♂️

**Comment by clavinjune** [comment]
can we merge this, so we can pick this one https://github.com/line/centraldogma-go/pull/49#issuecomment-1434440834 ? :bow:

**Comment by minwoox** [comment]
It's merged. Thanks a lot, again. 😄

**Comment by ikhoon** [comment]
Thanks, @clavinjune! I missed this PR. 😅

**Pull request merged**
